[[languages]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "rust"
[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "ruby"
[language-server.solargraph]
config = { diagnostics = true, formatting = true }

[[grammar]]
name = "slim"
source = { git = "https://github.com/kolen/tree-sitter-slim", rev = "4b8b4cf76a28ebdb45a48861d695f58459712ba2" }

[[language]]
name = "slim"
scope = "source.slim"
file-types = ["slim"]
grammar = "slim"
comment-tokens = ["#"]

[[language]]
name = "thor"
scope = "source.thor"
file-types = ["thor"]
grammar = "ruby"
comment-tokens = ["#"]
