export GPG_TTY=$(tty)

# brew zsh completions on fpath (must precede compinit)
if command -v brew >/dev/null 2>&1; then
  fpath=("$(brew --prefix)/share/zsh/site-functions" $fpath)
fi

autoload -Uz compinit && compinit -u

# Tool completions generated by shell-setup.sh (kubectl/fzf, *.zsh).
if [ -d "$HOME/.local/share/completions" ]; then
  for f in "$HOME/.local/share/completions/"*.zsh(N); do
    source "$f"
  done
fi

if [ -f $HOME/dotfiles/private/.zshrc ]; then
  source $HOME/dotfiles/private/.zshrc
fi

HISTFILE=$HOME/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
setopt SHARE_HISTORY HIST_IGNORE_DUPS

alias k=kubectl
compdef k=kubectl

alias ll='ls -lah'

alias so='source ~/.zshrc'
alias sp='source ~/.zprofile'

alias untar='tar -zxvf '

alias kaf="kubectl apply -f"
alias kad="kubectl delete -f"

kctx() { kubectl config use-context "$(kubectl config get-contexts -o name | fzf)" }
kns()  { kubectl config set-context --current --namespace "$(kubectl get ns -o name | cut -d/ -f2 | fzf)" }

export EDITOR='nvim'
export VISUAL='nvim'
alias vi=nvim
alias vim=nvim

alias lg='lazygit'

setopt PROMPT_SUBST
if [ -n "${DEVCONTAINER:-}" ]; then
  PROMPT='[%F{11}%*%f] %F{9}[${DEVCONTAINER}]%f %F{green}%~%f %F{12}󰅂%f '
else
  PROMPT='[%F{11}%*%f] %F{green}%~%f %F{12}󰅂%f '
fi
