export GPG_TTY=$(tty)

autoload -Uz compinit && compinit -u

# EDITOR=nvim contains "vi", which makes zsh pick vi keymap; force emacs (ctrl-f/ctrl-b).
bindkey -e

# ./install and dotfiles-update flags, parsed from the script's own usage comment
# (#   --flag  text). Any other `install` (coreutils) keeps its stock completion.
_dotfiles_install() {
  local f=$words[1]
  [[ -f $f ]] || f=${commands[$f]}
  if [[ -n $f ]] && grep -q '^# ./install' "$f" 2>/dev/null; then
    local -a flags
    flags=(${(f)"$(sed -nE 's/^#   (--[a-z-]+) +(.*)/\1[\2]/p' "$f")"})
    _arguments $flags
  else
    _install
  fi
}
compdef _dotfiles_install install dotfiles-update

# Tool completions generated by install (kubectl/fzf, *.zsh).
if [ -d "$HOME/.local/share/completions" ]; then
  for f in "$HOME/.local/share/completions/"*.zsh(N); do
    source "$f"
  done
fi

if [ -f $HOME/dotfiles/private/.zshrc ]; then
  source $HOME/dotfiles/private/.zshrc
fi

HISTFILE=$HOME/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
setopt SHARE_HISTORY HIST_IGNORE_DUPS

alias k=kubectl
compdef k=kubectl

alias ls='ls --color=auto'
alias ll='ls -lah'

alias so='source ~/.zshrc'
alias sp='source ~/.zprofile'

alias untar='tar -zxvf '

alias kaf="kubectl apply -f"
alias kad="kubectl delete -f"

# Esc in fzf picks nothing: do nothing rather than call kubectl with ""
kctx() { local c; c=$(kubectl config get-contexts -o name | fzf) && [ -n "$c" ] && kubectl config use-context "$c" }
kns()  { local n; n=$(kubectl get ns -o name | cut -d/ -f2 | fzf) && [ -n "$n" ] && kubectl config set-context --current --namespace "$n" }

alias vi=nvim
alias vim=nvim

alias lg='lazygit'

setopt PROMPT_SUBST
PROMPT='[%F{11}%*%f] %F{green}%~%f %F{12}󰅂%f '
