#!/bin/bash

# Update repo remote url
git remote set-url origin git@github.com:danilrwx/dotfiles.git

# Make symlinks for configs
mkdir -p ~/.config

ln -sf ~/dotfiles/.zshrc ~/

ln -sf ~/dotfiles/.gitconfig ~/
ln -sf ~/dotfiles/.gitignore_global ~/
ln -sf ~/dotfiles/.tmux.conf ~/.tmux.conf

ln -snf ~/dotfiles/config/vim ~/.vim
ln -snf ~/dotfiles/config/k9s ~/.config/
ln -snf ~/dotfiles/config/nvim ~/.config/
ln -snf ~/dotfiles/config/htop ~/.config/
ln -snf ~/dotfiles/config/lazygit ~/.config/

ln -sf ~/dotfiles/.zprofile ~/
ln -snf ~/dotfiles/config/i3 ~/.config/
ln -snf ~/dotfiles/config/dunst ~/.config/
ln -snf ~/dotfiles/config/xfce4 ~/.config/

# Update system
sudo apt update -y
sudo apt upgrade -y

# Install i3 with xorg
sudo apt install -y xorg xinit wireplumber pipewire pipewire-pulse pavucontrol pulseaudio-utils

# Install some software for i3
sudo apt install -y xcompmgr hsetroot	brightnessctl acpi maim xclip xsel lxappearance gtk-chtheme \
 libnotify-bin ncal

# Install base software
sudo apt install -y curl zip unzip gpg keychain ssh-askpass-gnome zsh fzf
sudo apt install -y libnss-extrausers openssh-server cron python3-distro python3-requests python3-crontab python3-pip python3-yaml

# Install ohmyzsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Setup keyboard layout
if [ ! -f /etc/X11/xorg.conf.d/00-keyboard.conf ]; then
cat << EOF | sudo tee -a /etc/X11/xorg.conf.d/00-keyboard.conf >> /dev/null
Section "InputClass"
	Identifier "system-keyboard"
	MatchIsKeyboard "on"
	Option "XkbLayout" "us,ru"
	Option "XkbModel" "pc105"
	Option "XkbOptions" "grp:ctr:_space_toggle"
EndSection
EOF
fi

# Setup amdgpu driver
if [ ! -f /etc/X11/xorg.conf.d/20-amdgpu.conf ]; then
	cat << EOF | sudo tee -a /etc/X11/xorg.conf.d/20-amdgpu.conf >> /dev/null
Section "Device"
	Identifier "AMD"
	Driver "amdgpu"
	Option "TearFree" "true"
	Option "DRI" "3"
EndSection
EOF
fi

# Install chrome
if [ ! -f /usr/bin/google-chrome ]; then
	curl -fSsL https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor | sudo tee /usr/share/keyrings/google-chrome.gpg >> /dev/null
	echo deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main | sudo tee /etc/apt/sources.list.d/google-chrome.list
	sudo apt update
	sudo apt install google-chrome-stable
fi

# Download Iosevka nerd font
if [ ! -f ~/.local/share/fonts/IosevkaNerdFont-Medium.ttf ]; then
	wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Iosevka.zip
	mkdir -p ~/.local/share/fonts
	cd ~/.local/share/fonts && unzip $(PWD)/Iosevka.zip
	rm $(PWD)/Iosevka.zip
	fc-cache -f
fi

# Install docker
if ! groups | grep -q '\bdocker\b'; then
	curl -fsSL get.docker.com | bash
	sudo systemctl start docker.socket
	sudo systemctl enable docker.socket
	sudo usermod -aG docker $USER
fi

# Install dev packages
sudo apt install -y golang gopls lazygit kubectl kubectx
