#!/bin/bash

# Update repo remote url
git remote set-url origin git@github.com:danilrwx/dotfiles.git

# Make symlinks for configs
mkdir -p ~/.config

ln -sf ~/dotfiles/.gitconfig ~/
ln -sf ~/dotfiles/.gitignore_global ~/
ln -sf ~/dotfiles/.tmux.conf ~/.tmux.conf

ln -snf ~/dotfiles/config/k9s ~/.config/
ln -snf ~/dotfiles/config/htop ~/.config/
ln -snf ~/dotfiles/config/lazygit ~/.config/
ln -snf ~/dotfiles/config/nvim ~/.config/

ln -sf ~/dotfiles/.zprofile ~/
ln -snf ~/dotfiles/config/i3 ~/.config/
ln -snf ~/dotfiles/config/dunst ~/.config/

# Update system
sudo apt update -y
sudo apt upgrade -y

# Install base software
sudo apt install -y curl zip unzip gpg keychain ssh-askpass-gnome zsh fzf neovim tigervnc-viewer

# Install ohmyzsh
if [ ! -d ~/.oh-my-zsh ]; then
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

rm ~/.zshrc
ln -sf ~/dotfiles/.zshrc ~/

# Download Iosevka nerd font
if [ ! -f ~/.local/share/fonts/IosevkaNerdFont-Medium.ttf ]; then
	wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Iosevka.zip
	mkdir -p ~/.local/share/fonts
	cd ~/.local/share/fonts && unzip $(PWD)/Iosevka.zip
	rm $(PWD)/Iosevka.zip
	fc-cache -f
fi

# Install docker
if ! groups | grep -q '\bdocker\b'; then
	curl -fsSL get.docker.com | bash
	sudo systemctl start docker.socket
	sudo systemctl enable docker.socket
	sudo usermod -aG docker $USER
fi

# Install virt-manager
if [ ! -f /usr/bin/virt-manager ]; then
	sudo apt install -y virt-manager
	sudo usermod -aG libvirt $USER
fi

# Setup flatpak
sudo apt install -y flatpak
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub -y org.telegram.desktop com.discordapp.Discord

# Install dev packages
sudo apt install -y nodejs golang gopls delve lazygit kubectl jq uuid-runtime

# Install go packages
go install github.com/derailed/k9s@latest
go install github.com/go-task/task/v3/cmd/task@latest
go install github.com/homeport/dyff/cmd/dyff@latest

go install github.com/nametake/golangci-lint-langserver@latest
go install mvdan.cc/gofumpt@latest
go install golang.org/x/tools/cmd/goimports@latest

go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8
go install github.com/onsi/ginkgo/v2/ginkgo@v2.14.0
go install github.com/matryer/moq@v0.4.0

# Install kubectl krew
if [ ! -d ~/.krew ]; then
	set -x; cd "$(mktemp -d)" &&
	OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
	ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
	KREW="krew-${OS}_${ARCH}" &&
	curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
	tar zxvf "${KREW}.tar.gz" &&
	./"${KREW}" install krew
fi

# Instal kubectl plugins
kubectl krew install ctx ns

# Install difftastic
if [ ! -f ~/.local/bin/difft ]; then
	curl -fsSL https://github.com/Wilfred/difftastic/releases/download/0.63.0/difft-x86_64-unknown-linux-gnu.tar.gz | tar xzv -C ~/.local/bin
fi

# Install lua-language-server
if [ ! -d ~/.local/share/lua-language-server ]; then
	mkdir -p ~/.local/share/lua-language-server
  curl -fsSL https://github.com/LuaLS/lua-language-server/releases/download/3.14.0/lua-language-server-3.14.0-linux-x64.tar.gz | tar xzv -C ~/.local/share/lua-language-server
  ln -s ~/.local/share/lua-language-server/bin/lua-language-server ~/.local/bin/lua-language-server
fi

# Install helm-ls
if [ ! -f ~/.local/bin/helm-ls ]; then
	curl -L https://github.com/mrjosh/helm-ls/releases/download/master/helm_ls_linux_amd64 --output ~/.local/bin/helm_ls
  chmod +x ~/.local/bin/helm_ls
fi
