#!/bin/bash

# Update repo remote url
git remote set-url origin git@github.com:danilrwx/dotfiles.git

# Make symlinks for configs
mkdir -p ~/.config

ln -sf ~/dotfiles/.gitconfig ~/
ln -sf ~/dotfiles/.gitignore_global ~/
ln -sf ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -snf ~/dotfiles/.vimrc ~/
ln -snf ~/dotfiles/.vim ~/

ln -snf ~/dotfiles/config/alacritty/ ~/.config/
ln -snf ~/dotfiles/config/k9s ~/.config/
ln -snf ~/dotfiles/config/htop ~/.config/
ln -snf ~/dotfiles/config/lazygit ~/.config/
ln -snf ~/dotfiles/config/nvim ~/.config/

# Install ohmyzsh
if [ ! -d ~/.oh-my-zsh ]; then
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

rm ~/.zshrc
ln -sf ~/dotfiles/.zshrc ~/

# Install go packages
go install github.com/derailed/k9s@latest
go install github.com/go-task/task/v3/cmd/task@latest
go install github.com/homeport/dyff/cmd/dyff@latest

go install github.com/nametake/golangci-lint-langserver@latest
go install mvdan.cc/gofumpt@latest
go install golang.org/x/tools/cmd/goimports@latest

go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8
go install github.com/onsi/ginkgo/v2/ginkgo@v2.14.0
go install github.com/matryer/moq@v0.4.0

# Install kubectl krew
if [ ! -d ~/.krew ]; then
	set -x; cd "$(mktemp -d)" &&
	OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
	ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
	KREW="krew-${OS}_${ARCH}" &&
	curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
	tar zxvf "${KREW}.tar.gz" &&
	./"${KREW}" install krew
fi

# Instal kubectl plugins
kubectl krew install ctx ns
