# -----------------------------------------------------------------------------
# K9s Gruvbox Light Skin
# Author: [@indiebrain](https://github.com/indiebrain)
# -----------------------------------------------------------------------------

# Styles...
foreground: &foreground "#24292e"
background: &background "#ffffff"
current_line: &current_line "#ebdbb2"
selection: &selection "#6a737d"
comment: &comment "#bdad93"
cyan: &cyan "#1b7c83"
green: &green "#22863a"
orange: &orange "#b08800"
magenta: &magenta "#6f42c1"
blue: &blue "#0366d6"
red: &red "#d73a49"

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *blue
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *orange
  info:
    fgColor: *magenta
    sectionColor: *foreground
  help:
    fgColor: *foreground
    bgColor: *background
    keyColor: *magenta
    numKeyColor: *blue
    sectionColor: *green
  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *magenta
    buttonFocusFgColor: *background
    buttonFocusBgColor: *cyan
    labelFgColor: *orange
    fieldFgColor: *foreground
  frame:
    border:
      fgColor: *selection
      focusColor: *current_line
    menu:
      fgColor: *foreground
      keyColor: *magenta
      numKeyColor: *magenta
    crumbs:
      fgColor: *background
      bgColor: *comment
      activeColor: *blue
    status:
      newColor: *cyan
      modifyColor: *blue
      addColor: *green
      errorColor: *red
      highlightColor: *orange
      killColor: *comment
      completedColor: *comment
    title:
      fgColor: *foreground
      bgColor: *background
      highlightColor: *orange
      counterColor: *blue
      filterColor: *magenta
  views:
    charts:
      bgColor: background
      defaultDialColors:
        - *blue
        - *red
      defaultChartColors:
        - *blue
        - *red
    table:
      fgColor: *foreground
      bgColor: *background
      cursorFgColor: *background
      cursorBgColor: *current_line
      header:
        fgColor: *foreground
        bgColor: *background
        sorterColor: *selection
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *current_line
      graphicColor: *blue
      showIcons: false
    yaml:
      keyColor: *magenta
      colonColor: *blue
      valueColor: *foreground
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *background
        toggleOnColor: *magenta
        toggleOffColor: *blue
