vim9script

filetype plugin indent on
syntax on

set autoindent
set expandtab
set tabstop=2
set shiftwidth=2
set hidden
set incsearch
set hlsearch
set number
set updatetime=100
set signcolumn=number
set shortmess=aoOtTI
set laststatus=0
set completeopt=menuone,noselect,noinsert,fuzzy,popup

if executable('ugrep')
  set grepprg=ugrep\ -RInk\ --tabs=1\ --ignore-files\ --exclude='zz_generated*'\ --exclude-dir='generated'
  set grepformat=%f:%l:%c:%m,%f+%l+%c+%m,%-G%f\\\|%l\\\|%c\\\|%m
else
  set grepprg=grep\ --exclude='*zz_generated*'\ --exclude-dir='generated'
endif

set backup
set backupdir=$XDG_CONFIG_HOME/vim/files/backup/
set backupext=-vimbackup
set backupskip=
set directory=$XDG_CONFIG_HOME/vim/files/swap/
set updatecount=100
set undofile
set undodir=$XDG_CONFIG_HOME/vim/files/undo/

match errorMsg '\s\+$'

silent! colorscheme torte

highlight Normal ctermbg=none
highlight SignColumn ctermbg=none
highlight LineNr ctermfg=244 guifg=#808080
highlight Pmenu ctermbg=black ctermfg=252 guibg=#000000 guifg=#d0d0d0
highlight PmenuSel ctermbg=252 ctermfg=black guibg=#d0d0d0 guifg=#000000

silent! packadd! cfilter
silent! packadd! comment
silent! packadd! hlyank

g:mapleader = " "

nnoremap <c-d> <c-d>zz<cr>
nnoremap <c-u> <c-u>zz<cr>

nnoremap <c-l> :nohl<cr>

nnoremap <silent> - <cmd>Oil<cr>

nnoremap <silent> <leader>gg <cmd>silent execute '!tmux neww lazygit'<bar>redraw!<cr>

# terminals send Alt-q as <Esc>q; teach vim the sequence so <A-q> actually fires
execute "set <A-q>=\eq"
nnoremap <silent> <A-q> <cmd>bd<cr>
nnoremap <silent> <S-l> <cmd>bn<cr>
nnoremap <silent> <S-h> <cmd>bp<cr>

