vim9script

filetype plugin indent on
syntax on

set autoindent
set expandtab
set tabstop=2
set shiftwidth=2
set hidden
set incsearch
set hlsearch
set number
set updatetime=100
set signcolumn=yes
set shortmess=aoOtTI
set laststatus=0

if executable('ugrep')
  set grepprg=ugrep\ -RInk\ --tabs=1\ --ignore-files\ --exclude='zz_generated*'\ --exclude-dir='generated'
  set grepformat=%f:%l:%c:%m,%f+%l+%c+%m,%-G%f\\\|%l\\\|%c\\\|%m
else
  set grepprg=grep\ --exclude='*zz_generated*'\ --exclude-dir='generated'
endif

set backup
set backupdir=$XDG_CONFIG_HOME/vim/files/backup/
set backupext=-vimbackup
set backupskip=
set directory=$XDG_CONFIG_HOME/vim/files/swap/
set updatecount=100
set undofile
set undodir=$XDG_CONFIG_HOME/vim/files/undo/

match errorMsg '\s\+$'

highlight Normal ctermbg=none
highlight SignColumn ctermbg=none
highlight Pmenu ctermbg=black ctermfg=252 guibg=#000000 guifg=#d0d0d0
highlight PmenuSel ctermbg=252 ctermfg=black guibg=#d0d0d0 guifg=#000000

silent! packadd! cfilter
silent! packadd! comment
silent! packadd! hlyank

# fzf ships a base vim plugin (:FZF, fzf#run) — load it from the install, no clone.
# brew keeps it under <prefix>/plugin (add to rtp); apt ships it as a standalone
# file (source directly). /usr/share/vim/vimfiles is already in rtp, so skip it.
var fzf_loaded = false
for d in ['/opt/homebrew/opt/fzf', '/usr/local/opt/fzf', '/home/linuxbrew/.linuxbrew/opt/fzf', expand('~/.fzf')]
  if isdirectory(d)
    execute 'set runtimepath+=' .. d
    fzf_loaded = true
    break
  endif
endfor
if !fzf_loaded
  for f in ['/usr/share/vim/vimfiles/plugin/fzf.vim', '/usr/share/doc/fzf/examples/fzf.vim']
    if filereadable(f)
      if f !~ '/vimfiles/'
        execute 'source ' .. f
      endif
      break
    endif
  endfor
endif

g:mapleader = " "

nnoremap <c-d> <c-d>zz<cr>
nnoremap <c-u> <c-u>zz<cr>

nnoremap <c-l> :nohl<cr>

nnoremap <silent> <leader>f :FZF<cr>

nnoremap <silent> - <cmd>Oil<cr>

var lspOpts = {
	autoHighlightDiags: true,
	useQuickfixForLocations: true,
	semanticHighlight: true,
	showInlayHints: false,
}

autocmd User LspSetup call LspOptionsSet(lspOpts)

var lspServers = [{
	name: 'golang',
	filetype: ['go', 'gomod'],
	path: exepath('gopls'),
	args: ['serve'],
	syncInit: false,
	workspaceConfig: {
		gopls: {
			hints: {
				assignVariableTypes: true,
				compositeLiteralFields: true,
				compositeLiteralTypes: true,
				constantValues: true,
				functionTypeParameters: true,
				parameterNames: true,
				rangeVariableTypes: true,
				semanticTokens: false
			}
		}
	}
},
{
  name: 'clangd',
  filetype: ['c', 'cpp'],
  path: exepath('clangd'),
  args: ['--background-index']
},
]

autocmd User LspSetup call LspAddServer(lspServers)

def On_lsp_buffer_enabled()
  setlocal omnifunc=g:LspOmniFunc
  setlocal tagfunc=lsp#lsp#TagFunc
  setlocal formatexpr=lsp#lsp#FormatExpr()

  nnoremap grr :LspShowReferences<cr>
  nnoremap gri :LspPeekImpl<cr>
  nnoremap K   :LspHover<cr>
  nnoremap grs :LspDocumentSymbol<cr>
  nnoremap grS :LspSymbolSearch<cr>
  nnoremap gra :LspCodeAction<cr>
  nnoremap grc :LspCodeLens<cr>
  nnoremap grn :LspRename<cr>
  nnoremap grf :LspFormat<cr>
  nnoremap <c-w>d :LspDiag current<cr>
  nnoremap [d :LspDiag prev<cr>
  nnoremap ]d :LspDiag next<cr>

  autocmd! BufWritePre *.go call execute('LspFormat')
enddef
autocmd User LspAttached call On_lsp_buffer_enabled()

