vim9script

set nocompatible

# Load plugins from ~/.vim/pack/*/start (cloned by shell-setup.sh). The XDG
# config dir is a symlink into this repo, so keep plugins out of it.
execute "set packpath^=" .. expand("~/.vim")

filetype plugin indent on # Load plugins according to detected filetype.
syntax on                  # Enable syntax highlighting.

set autoindent             # Indent according to previous line.
set expandtab              # Use spaces instead of tabs.
set tabstop=2              # Use 2 spaces for indenting.
set softtabstop=2          # Tab key indents by 2 spaces.
set shiftwidth=2           # >> indents by 2 spaces.
set shiftround             # >> indents to next multiple of 'shiftwidth'.

set backspace=indent,eol,start # Make backspace work as you would expect.
set hidden                 # Switch between buffers without having to save first.
set display=lastline       # Show as much as possible of the last line.

set showcmd                # Show already typed keys when more are expected.

set incsearch              # Highlight while searching with / or ?.
set hlsearch               # Keep matches highlighted.

set number                 # Set line numbers
set relativenumber         # Set relative linenumbers

set updatetime=100         # Fast redraw
set signcolumn=yes         # Always render signcolumn
set shortmess=aoOtTI       # Avoid most of the 'Hit Enter ...' messages
set wildmenu               # Better command-line completion
set mouse=a                # Enable mouse support
set laststatus=0           # Disable status bar

if executable('ugrep')
  set grepprg=ugrep\ -RInk\ --tabs=1\ --ignore-files\ --exclude='zz_generated*'\ --exclude-dir='generated'
  set grepformat=%f:%l:%c:%m,%f+%l+%c+%m,%-G%f\\\|%l\\\|%c\\\|%m
else
  set grepprg=grep\ --exclude='*zz_generated*'\ --exclude-dir='generated'
endif

# Put all temporary files under the same directory.
# https://github.com/mhinz/vim-galore#temporary-files
set backup
set backupdir=$XDG_CONFIG_HOME/vim/files/backup/
set backupext=-vimbackup
set backupskip=
set directory=$XDG_CONFIG_HOME/vim/files/swap/
set updatecount=100
set undofile
set undodir=$XDG_CONFIG_HOME/vim/files/undo/

# mark trailing spaces as errors
match errorMsg '\s\+$'

colorscheme torte
highlight Normal ctermbg=none
highlight SignColumn ctermbg=none
highlight DiffAdd ctermfg=16
highlight DiffChange ctermfg=16
highlight DiffDelete ctermfg=16

silent! packadd! cfilter
silent! packadd! comment
silent! packadd! hlyank

g:mapleader = " "

nnoremap <silent> <leader>q :call ToggleQuickFix()<cr>
nnoremap <c-j> :cnext<cr>
nnoremap <c-k> :cprev<cr>

nnoremap <c-d> <c-d>zz<cr>
nnoremap <c-u> <c-u>zz<cr>

nnoremap <c-l> :nohl<cr>

nnoremap <silent> <leader>tr :TestNearest<cr>
nnoremap <silent> <leader>tt :TestFile<cr>

nnoremap <silent> <leader>gl :tab Git log --follow -p %<cr>
nnoremap <silent> <leader>gL :tab Git log<cr>
nnoremap <silent> <leader>gb :tab Git blame<cr>

nnoremap <silent> ghs <cmd>GitGutterStageHunk<cr>
nnoremap <silent> ghu <cmd>GitGutterUndoHunk<cr>
nnoremap <silent> ghp <cmd>GitGutterPreviewHunk<cr>

nnoremap <silent> - <cmd>Dir<cr>

execute "set <A-q>=\eq"
nnoremap <a-q> :bd<cr>

g:gitgutter_sign_priority = 0
g:gitgutter_preview_win_floating = 1

var lspOpts = {
	autoHighlightDiags: true,
	useQuickfixForLocations: true,
	semanticHighlight: true,
	showInlayHints: false,
}

autocmd User LspSetup call LspOptionsSet(lspOpts)

var lspServers = [{
	name: 'golang',
	filetype: ['go', 'gomod'],
	path: exepath('gopls'),
	args: ['serve'],
	syncInit: false,
	workspaceConfig: {
		gopls: {
			hints: {
				assignVariableTypes: true,
				compositeLiteralFields: true,
				compositeLiteralTypes: true,
				constantValues: true,
				functionTypeParameters: true,
				parameterNames: true,
				rangeVariableTypes: true,
				semanticTokens: false
			}
		}
	}
},
{
  name: 'clangd',
  filetype: ['c', 'cpp'],
  path: exepath('clangd'),
  args: ['--background-index']
},
]

autocmd User LspSetup call LspAddServer(lspServers)

def On_lsp_buffer_enabled()
  setlocal omnifunc=g:LspOmniFunc
  setlocal tagfunc=lsp#lsp#TagFunc
  setlocal formatexpr=lsp#lsp#FormatExpr()

  nnoremap grr :LspShowReferences<cr>
  nnoremap gri :LspPeekImpl<cr>
  nnoremap K   :LspHover<cr>
  nnoremap grs :LspDocumentSymbol<cr>
  nnoremap grS :LspSymbolSearch<cr>
  nnoremap gra :LspCodeAction<cr>
  nnoremap grc :LspCodeLens<cr>
  nnoremap grn :LspRename<cr>
  nnoremap grf :LspFormat<cr>
  nnoremap <c-w>d :LspDiag current<cr>
  nnoremap [d :LspDiag prev<cr>
  nnoremap ]d :LspDiag next<cr>

  autocmd! BufWritePre *.go call execute('LspFormat')
enddef
autocmd User LspAttached call On_lsp_buffer_enabled()

def g:ToggleQuickFix()
  if empty(filter(getwininfo(), 'v:val.quickfix'))
    copen
  else
    cclose
  endif
enddef

