#!/bin/bash

vol() {
  icon="󰕾"
  vol=`pactl get-sink-volume @DEFAULT_SINK@ | awk '{ print $5 }'`

  muted=`pactl get-sink-mute @DEFAULT_SINK@ | awk '{ print $2 }'`
  [[ $muted = "yes" ]] && icon="󰝟"

  echo -e "$icon $vol"
}

mic() {
  icon="󰍬"
  vol=`pactl get-source-volume @DEFAULT_SOURCE@ | awk '{ print $5 }'`

  muted=`pactl get-source-mute @DEFAULT_SOURCE@ | awk '{ print $2 }'`
  [[ $muted = "yes" ]] && icon="󰍭"

  echo -e "$icon $vol"
}

bat_icon() {
  local bat="/sys/class/power_supply/BAT$1"
  local vol="$(cat "$bat/capacity")"
  local status="$(cat "$bat/status")"

  local result="󰁹"
  [[ $status = "Charging" ]] && result="󰂅"

  if [[ $vol -lt 90 ]]; then
    result="󰂂"
    [[ $status = "Charging" ]] && result="󰂋"
  fi

  if [[ $vol -lt 80 ]]; then
    result="󰂁"
    [[ $status = "Charging" ]] && result="󰂊"
  fi

  if [[ $vol -lt 70 ]]; then
    result="󰂀"
    [[ $status = "Charging" ]] && result="󰢞"
  fi

  if [[ $vol -lt 60 ]]; then
    result="󰁿"
    [[ $status = "Charging" ]] && result="󰂉"
  fi

  if [[ $vol -lt 50 ]]; then
    result="󰁾"
    [[ $status = "Charging" ]] && result="󰢝"
  fi

  if [[ $vol -lt 40 ]]; then
    result="󰁽"
    [[ $status = "Charging" ]] && result="󰂈"
  fi

  if [[ $vol -lt 30 ]]; then
    result="󰁼"
    [[ $status = "Charging" ]] && result="󰂇"
  fi

  if [[ $vol -lt 20 ]]; then
    result="󰁻"
    [[ $status = "Charging" ]] && result="󰂆"
  fi

  if [[ $vol -lt 10 ]]; then
    result="󰁺"
    [[ $status = "Charging" ]] && result="󰢜"
  fi

  echo "$result"
}

bat0() {
  res=""

  if [[ -d /sys/class/power_supply/BAT0/ ]]; then
    bat0=`cat /sys/class/power_supply/BAT0/capacity`
    icon0="$(bat_icon 0)"
    res+="$icon0 $bat0"
  fi

  echo -e "$res"
}

bat1() {
  res=""

  if [[ -d /sys/class/power_supply/BAT1/ ]]; then
    bat1=`cat /sys/class/power_supply/BAT1/capacity`
    icon1="$(bat_icon 1)"
    res+="$icon1 $bat1"
  fi

  echo -e "$res"
}

bri() {
  c=`brightnessctl get`
  m=`brightnessctl max`
  bri=`printf "%.0f" $(echo "scale=1; ($c / $m) * 100" | bc)`
  echo -e "  $bri%"
}

del() {
  echo -e "  "
}

dete() {
  echo -e `date`
}

mem() {
  val=`free -h | awk '/Mem/{print $3}'`
  icon="󰍛"

  echo -e "$icon $val"
}

vpn() {
  status=`ip link | grep vpn | wc -l`
  icon="󰅛"
  text="DOWN"

  [[ $status -gt 0 ]] && icon="󰱓" && text="UP"

  echo -e "$icon $text"
}

keyboard() {
  icon="󰥻"
  text="US"

  echo -e "$icon $text"
}

SLEEP_SEC=0.5
while true; do
  echo "$(vpn) $(del) $(vol) $(del) $(mic) $(del) $(bat0) $(del) $(bat1) $(del) $(bri) $(del) $(keyboard) $(del) $(date)  "
  sleep $SLEEP_SEC
done
