# dotfiles: the touchpad under i3
Section "InputClass"
    Identifier "touchpad"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "Tapping" "off"
    Option "NaturalScrolling" "true"
    Option "ClickMethod" "clickfinger"
    Option "DisableWhileTyping" "true"
    Option "AccelSpeed" "-0.25"
    Option "ScrollPixelDistance" "50"
EndSection
