k9s:
  cluster: amethyst
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
    - cloudnative-pg
    - questions
  view:
    active: context
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
