font_family Iosevka Nerd Font Mono
font_size 12.0

# vertical horizontal
window_padding_width 5 5

scrollback_lines 20000
scrollbar hovered
macos_titlebar_color dark
macos_option_as_alt yes

include base.conf
