#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

hsetroot -cover ~/Backgrounds/2.jpg
dex --autostart --environment bspwm &
dunst -conf ~/.config/dunst/dunstrc &
xsetroot -cursor_name left_ptr &
xcompmgr &

bspc monitor -d I II III IV V

bspc config border_width         1
bspc config window_gap           0

bspc config normal_border_color  "#23252e"
bspc config active_border_color  "#ebdbb2"
bspc config focused_border_color "#ebdbb2"

bspc config split_ratio          0.52

bspc config single_monocle	     true
bspc config gapless_monocle      true
bspc config borderless_monocle   true
bspc config paddingless_monocle	 true

bspc config focus_follows_pointer true

bspc rule -a Chromium desktop='^1'
bspc rule -a dmenu rectangle=900x22+610+90
