k9s:
  cluster: lilian
  namespace:
    active: questions
    lockFavorites: false
    favorites:
    - all
    - questions
  view:
    active: pod
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
