#!/bin/bash

vol() {
	icon="󰕾"
	vol=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{ print $5 }')

	muted=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{ print $2 }')
	[[ $muted = "yes" ]] && icon="󰝟"

	echo -e " $icon $vol"
}

mic() {
	icon="󰍬"
	vol=$(pactl get-source-volume @DEFAULT_SOURCE@ | awk '{ print $5 }')

	muted=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{ print $2 }')
	[[ $muted = "yes" ]] && icon="󰍭"

	echo -e " $icon $vol"
}

bat_icon() {
	local bat="/sys/class/power_supply/BAT$1"
	local vol="$(cat "$bat/capacity")"
	local status="$(cat "$bat/status")"

	local result="󰁹"
	[[ $status = "Charging" ]] && result="󰂅"

	if [[ $vol -lt 90 ]]; then
		result="󰂂"
		[[ $status = "Charging" ]] && result="󰂋"
	fi

	if [[ $vol -lt 80 ]]; then
		result="󰂁"
		[[ $status = "Charging" ]] && result="󰂊"
	fi

	if [[ $vol -lt 70 ]]; then
		result="󰂀"
		[[ $status = "Charging" ]] && result="󰢞"
	fi

	if [[ $vol -lt 60 ]]; then
		result="󰁿"
		[[ $status = "Charging" ]] && result="󰂉"
	fi

	if [[ $vol -lt 50 ]]; then
		result="󰁾"
		[[ $status = "Charging" ]] && result="󰢝"
	fi

	if [[ $vol -lt 40 ]]; then
		result="󰁽"
		[[ $status = "Charging" ]] && result="󰂈"
	fi

	if [[ $vol -lt 30 ]]; then
		result="󰁼"
		[[ $status = "Charging" ]] && result="󰂇"
	fi

	if [[ $vol -lt 20 ]]; then
		result="󰁻"
		[[ $status = "Charging" ]] && result="󰂆"
	fi

	if [[ $vol -lt 10 ]]; then
		result="󰁺"
		[[ $status = "Charging" ]] && result="󰢜"
	fi

	echo "$result"
}

bat0() {
	res=""

	if [[ -d /sys/class/power_supply/BAT0/ ]]; then
		bat0=$(cat /sys/class/power_supply/BAT0/capacity)
		icon0="$(bat_icon 0)"
		res+="$icon0 $bat0%"

		echo -e " $(del)$res"
	fi
}

bat1() {
	res=""

	if [[ -d /sys/class/power_supply/BAT1/ ]]; then
		bat1=$(cat /sys/class/power_supply/BAT1/capacity)
		icon1="$(bat_icon 1)"
		res+="$icon1 $bat1%"

		echo -e " $(del)$res"
	fi
}

bri() {
	if [[ -e /usr/bin/brightnessctl ]]; then
		c=$(brightnessctl get)
		m=$(brightnessctl max)
		bri=$(printf "%.0f" $(echo "scale=1; ($c / $m) * 100" | bc))
		echo -e "$(del)   $bri%"
	fi
}

del() {
	echo -e "  "
}

dete() {
	echo -e $(date)
}

mem() {
	val=$(free -h | awk '/Память/{print $3}')
	icon="󰍛"

	echo -e " $icon $val"
}

vpn() {
	status=$(ip link | grep vpn | wc -l)
	icon="󰅛"
	text="DOWN"

	[[ $status -gt 0 ]] && icon="󰱓" && text="UP"

	echo -e " $icon $text"
}

keyboard() {
	icon="󰌌"
	text=$(xkblayout-state print "%s" | awk '{print toupper($0)}')

	echo -e " $icon $text"
}

SLEEP_SEC=1
while true; do
	text="$(mem)$(del)$(vol)$(del)$(mic)$(bat0)$(bat1)$(bri)$(del)$(keyboard)$(del)$(date)  "
	xsetroot -name "${text}"

	sleep $SLEEP_SEC
done
