#!/bin/env bash

log() {
  echo -e "\033[0;31m$1\033[0m"
}

OS=$(uname -s)
if [[ "$OS" != "Linux" ]]; then
  exit 0
fi

if [ -f /etc/os-release ]; then
    . /etc/os-release

    if [ "$ID" == "ubuntu" ]; then
      log "This is a Ubuntu system."
    elif [ "$ID" == "debian" ]; then
      log "This is a Debian system."
    elif [ "$ID" == "fedora" ]; then
      log "This is a Fedora system."
    else
      exit 1
    fi
else
  exit 1
fi
