let mapleader = "\<Space>"

if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
  silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Тема
Plug 'RRethy/nvim-base16'
Plug 'rktjmp/lush.nvim'
Plug '~/dotfiles/files/theme'

" Нижняя панель
" Plug 'vim-airline/vim-airline'
" Plug 'dawikur/base16-vim-airline-themes'

" Стартовый экран
Plug 'mhinz/vim-startify'

" Быстрый поиск
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Файловый менеджер
Plug 'kevinhwang91/rnvimr'

" Удобные комментарии
Plug 'preservim/nerdcommenter'

" Асинхронный линтер
Plug 'dense-analysis/ale'

" LSP
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'fannheyward/coc-marketplace'
Plug 'sheerun/vim-polyglot'

" Запуск кода
Plug 'michaelb/sniprun', {'do': 'bash install.sh'}

" Добавляет end в конец блока
Plug 'tpope/vim-endwise'

" Переключение раскладки в insert
Plug 'rlue/vim-barbaric'

" Дебаггер
Plug 'puremourning/vimspector'

" Терминал
Plug 'akinsho/toggleterm.nvim'

" Подсветка синтаксиса
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}

" Для руби
Plug 'tpope/vim-rails'
Plug 'vim-ruby/vim-ruby'
Plug 'tpope/vim-bundler'
Plug 'slim-template/vim-slim'

" Для JS
Plug 'pangloss/vim-javascript'
Plug 'moll/vim-node'

" Поддержка ctags
Plug 'xolox/vim-misc'
Plug 'xolox/vim-easytags'

" Подсветка парных тегов
Plug 'Valloric/MatchTagAlways'

" Подсветка лишних пробелов
Plug 'ntpeters/vim-better-whitespace'

" Великий гит
Plug 'kdheepak/lazygit.nvim'
Plug 'tpope/vim-fugitive'

" Подсветка изменений гита
Plug 'lewis6991/gitsigns.nvim'

" Найти и заменить
Plug 'windwp/nvim-spectre'

" Плавный скролл
Plug 'karb94/neoscroll.nvim'

" Подсветка отступов
Plug 'nathanaelkane/vim-indent-guides'

" Зависимости для popup плагинов
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-lua/popup.nvim'

let g:coc_global_extensions = [
      \ 'coc-tsserver',
      \ 'coc-prettier',
      \ 'coc-html',
      \ 'coc-lists',
      \ 'coc-xml',
      \ 'coc-sh',
      \ 'coc-css',
      \ 'coc-stylelint',
      \ 'coc-vimlsp',
      \ 'coc-go',
      \ 'coc-json',
      \ 'coc-eslint',
      \ 'coc-solargraph',
      \ 'coc-yaml',
      \ 'coc-highlight',
      \ 'coc-snippets',
      \ 'coc-diagnostic',
      \ 'coc-yank',
      \]

call plug#end()

source ~/dotfiles/files/vim-configs/base.vim
source ~/dotfiles/files/vim-configs/fzf.vim
source ~/dotfiles/files/vim-configs/ale.vim
source ~/dotfiles/files/vim-configs/coc.vim
source ~/dotfiles/files/vim-configs/coc-plugins.vim
source ~/dotfiles/files/vim-configs/debugger.vim
source ~/dotfiles/files/vim-configs/spectre.vim
source ~/dotfiles/files/vim-configs/gitsigns.vim
source ~/dotfiles/files/vim-configs/terminal.vim
