let mapleader = "\<Space>"

if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
  silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

"Тема
Plug 'joshdick/onedark.vim'

" Нижняя панель
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Стартовый экран
Plug 'mhinz/vim-startify'

" Быстрый поиск
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Файловый менеджер
Plug 'scrooloose/nerdtree'

" Удобные комментарии
Plug 'preservim/nerdcommenter'

" Асинхронный линтер
Plug 'dense-analysis/ale'

" LSP
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Добавляет end в конец блока
Plug 'tpope/vim-endwise'

" Переключение раскладки в insert
Plug 'rlue/vim-barbaric'

" Дебаггер
Plug 'puremourning/vimspector'

" Терминал
Plug 'kassio/neoterm'

" Подсветка синтаксиса
Plug 'sheerun/vim-polyglot'

" Для руби
Plug 'tpope/vim-rails'
Plug 'vim-ruby/vim-ruby'
Plug 'tpope/vim-bundler'
Plug 'slim-template/vim-slim'

" Для JS
Plug 'pangloss/vim-javascript'
Plug 'moll/vim-node'

" Поддержка ctags
Plug 'xolox/vim-misc'
Plug 'xolox/vim-easytags'

" Подсветка парных тегов
Plug 'Valloric/MatchTagAlways'

let g:coc_global_extensions = [
      \ 'coc-angular',
      \ 'coc-markdownlint',
      \ 'coc-tsserver',
      \ 'coc-prettier',
      \ 'coc-html',
      \ 'coc-lists',
      \ 'coc-xml',
      \ 'coc-sh',
      \ 'coc-css',
      \ 'coc-stylelint',
      \ 'coc-vimlsp',
      \ 'coc-go',
      \ 'coc-elixir',
      \ 'coc-json',
      \ 'coc-eslint',
      \ 'coc-jest',
      \ 'coc-solargraph',
      \ 'coc-yaml',
      \ 'coc-highlight',
      \ 'coc-snippets',
      \ 'coc-diagnostic',
      \ 'coc-yank',
      \ 'coc-git',
      \]

call plug#end()

source ~/dotfiles/files/vim-configs/base.vim
source ~/dotfiles/files/vim-configs/nerdtree.vim
source ~/dotfiles/files/vim-configs/fzf.vim
source ~/dotfiles/files/vim-configs/ale.vim
source ~/dotfiles/files/vim-configs/coc.vim
source ~/dotfiles/files/vim-configs/coc-plugins.vim
