promptToReturnFromSubprocess: false
disableStartupPopups: true
# installed by `go install` (install), which also updates it
update:
  method: never
gui:
  nerdFontsVersion: "3"
git:
  commit:
    signOff: true
  autoFetch: false
  autoRefresh: false
services:
  "fox.flant.com": "gitlab:fox.flant.com"
