k9s:
  liveViewAutoRefresh: true
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  ui:
    enableMouse: true
    headless: false
    logoless: true
    crumbsless: false
    noIcons: false
    reactive: true
    skin: light
