theme = "github_light_transparent"

[editor]
bufferline              = "multiple"
rulers                  = [80]
shell                   = ["/bin/bash", "-c"]
line-number             = "relative"
lsp.display-inlay-hints = false

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "version-control"]
center = ["diagnostics", "spinner", "file-name", "file-modification-indicator"]
right = ["workspace-diagnostics", "selections", "separator", "position", "separator", "file-line-ending", "separator", "file-type"]
separator = "|"
mode.normal = "Нормальный"
mode.insert = "Вставка"
mode.select = "Визуальный"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-g = ":sh topen-git"
C-p = ":sh topen-lf"
C-t = ":sh topen-bash"
A-f = ":format"
A-q = ":buffer-close"
A-w = [
    "save_selection",
    "select_all",
    # Delete trailing whitespace from end of each line
    ":pipe sed 's/[ \t]*$//'",
    # Delete trailing blank lines (including whitespace) from end of the buffer
    ":pipe awk '/^\\s*$/ {b=b $0 \"\\n\"; next;} {printf \"%s\",b; b=\"\"; print;}'",
    "collapse_selection",
    "keep_primary_selection",
    ":write",
]
