[tools]
go = "1.25"
node = "lts"
jq = "latest"
ripgrep = "latest"
fzf = "latest"
golangci-lint = "latest"
kubectl = "latest"
helm = "latest"
k9s = "latest"
gh = "latest"
glab = "latest"
yq = "latest"
lazygit = "latest"
neovim = "latest"
task = "latest"
crane = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/matryer/moq" = "latest"
"go:github.com/onsi/ginkgo/v2/ginkgo" = "2.14.0"
"go:github.com/nametake/golangci-lint-langserver" = "latest"
lua-language-server = "latest"
rust-analyzer = "latest"
helm-ls = "latest"
"npm:bash-language-server" = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"ubi:deckhouse/deckhouse-cli" = { version = "latest", exe = "d8" }
